# Generated by Django 5.1.11 on 2025-07-12 14:34

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_sitesetup_faveicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='faveicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/', validators=[utils.model_validators.validate_png]),
        ),
    ]
